name: Merge vsajip/master

on:
  schedule:
    - cron: "5 4 * * *" # Run once a day
  workflow_dispatch: # Allow manual triggering

jobs:
  merge-original:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Check for upstream changes
        id: check-changes
        run: |
          echo "> git remote add"
          git remote add vsajip https://github.com/vsajip/python-gnupg.git
          echo "> git fetch"
          git fetch vsajip

          # Check if there are new commits in upstream
          UPSTREAM_COMMIT=$(git rev-parse vsajip/master)
          CURRENT_COMMIT=$(git rev-parse HEAD)

          if [ "$UPSTREAM_COMMIT" = "$CURRENT_COMMIT" ]; then
            echo "No new commits in upstream (same commit)"
            echo "has-changes=false" >> $GITHUB_OUTPUT
          elif git merge-base --is-ancestor HEAD vsajip/master; then
            echo "No new commits in upstream (current branch is behind)"
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            echo "New commits found in upstream"
            echo "has-changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Merge remote
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          echo "> git merge (no commit)"
          git merge vsajip/master --allow-unrelated-histories --strategy-option theirs --no-commit --no-edit
          echo "> rm undesired workflow"
          rm -f .github/workflows/python-package.yml # Don't need in my repo

      - name: Move to to module layout
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          mkdir -p gnupg
          touch gnupg/py.typed
          if [ -f gnupg.py ]; then
            echo "> mv gnupg.py gnupg/__init__.py"
            mv gnupg.py gnupg/__init__.py
          fi

      - name: Update setup.cfg
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          sed -i '/^py_modules = gnupg$/{
              s/^py_modules = gnupg$/packages = gnupg\npackage_dir =\n    = ./
          }' setup.cfg

      - name: Add *.egg-info to gitignore, fix newlines
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          grep -qxF '*.egg-info' .gitignore || echo '*.egg-info' >> .gitignore
          sed -i '/^$/d' .gitignore && printf '\n' >> .gitignore

      - name: Commit and Push Changes
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          echo "> git add"
          git add .
          echo "> git commit"
          git commit -m "Merge vsajip/master and rename gnupg.py → gnupg/__init__.py"
          echo "> git push"
          git push origin master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
