name: Merge vsajip/master

on:
  schedule:
    - cron: "5 4 * * *" # Run once a day
  workflow_dispatch: # Allow manual triggering

jobs:
  merge-original:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Merge remote vsajip/python-gnupg
        run: |
          echo "> git remote add"
          git remote add vsajip https://github.com/vsajip/python-gnupg.git
          echo "> git fetch"
          git fetch vsajip
          echo "> git merge (no commit)"
          git merge vsajip/master --allow-unrelated-histories --strategy-option theirs --no-commit --no-edit

      - name: Remove undesired workflow for this repo
        run: rm -f .github/workflows/python-package.yml

      - name: Move to to module layout
        run: |
          mkdir -p gnupg
          touch gnupg/py.typed
          if [ -f gnupg.py ]; then
            echo "> mv gnupg.py gnupg/__init__.py"
            mv gnupg.py gnupg/__init__.py
          fi

      - name: Update setup.cfg
        run: |
          sed -i '/^py_modules = gnupg$/{
              s/^py_modules = gnupg$/packages = gnupg\npackage_dir =\n    = .\n\n[options.package_data]\ngnupg = py.typed, *.pyi/
          }' setup.cfg

      - name: Add *.egg-info to gitignore, fix newlines
        run: |
          grep -qxF '*.egg-info' .gitignore || echo '*.egg-info' >> .gitignore
          sed -i '/^$/d' .gitignore && printf '\n' >> .gitignore

      - name: Commit and Push Changes
        run: |
          echo "> git add"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit, skipping push"
          else
            echo "> git commit"
            git commit -m "Merge vsajip/master and rename gnupg.py → gnupg/__init__.py"
            echo "> git push"
            git push origin master --force
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
